on: ["push"]
jobs:

  
  fuzzer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        pip3 install numpy
        pip3 install os
        pip3 install sys
        pip3 install pandas
        pip3 install datetime
        pip3 install statistics 
        pip3 install GitPython
        # Install dependencies from requirements.txt
        # Install any additional dependencies needed for the fuzzer
    - name: Run Fuzzer
      run: |
        # Command to run your fuzzer
        python fuzz.py
